/*
 * generated by Xtext 2.17.1
 */
package com.mimacom.ddd.sm.sus.ide

import com.google.inject.Guice
import com.mimacom.ddd.sm.sus.SusRuntimeModule
import com.mimacom.ddd.sm.sus.SusStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class SusIdeSetup extends SusStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new SusRuntimeModule, new SusIdeModule))
	}
	
}
