/*
 * generated by Xtext 2.16.0
 */
package com.mimacom.ddd.sm.sim.tests

import com.google.inject.Inject
import com.google.inject.Provider
import com.mimacom.ddd.dm.base.DNamespace
import org.eclipse.emf.ecore.resource.ResourceSet
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(SimInjectorProvider)
class SimParsingTest {
	@Inject 
	ParseHelper<DNamespace> dmxParseHelper
	
	@Inject 
	ParseHelper<DNamespace> dmParseHelper
	
	@Inject 
	ParseHelper<DNamespace> smParseHelper
	
	@Inject
	Provider<ResourceSet> resourceSetProvider
	
	@Test
	def void grabArchetype() {
		val resourceSet = resourceSetProvider.get
		dmxParseHelper.fileExtension = ".dmx"
		val dmx = dmxParseHelper.parse('''
			namespace dm.types
			archetype DT is NUMBER
		''', resourceSet)
		val dm = dmParseHelper.parse('''
			domain DM
			information model IM {
				archetype DT { }
			}
		''', resourceSet)
		val sm = smParseHelper.parse('''
			namespace
			base information model SM {
				grab primitive DM.DT as ST 
			}
		''', resourceSet)
		Assertions.assertNotNull(dmx)
		val dmxErrors = dmx.eResource.errors
		Assertions.assertTrue(dmxErrors.isEmpty, '''Unexpected errors in dmx: «dmxErrors.join(", ")»''')
		Assertions.assertNotNull(dm)
		val dmErrors = dm.eResource.errors
		Assertions.assertTrue(dmErrors.isEmpty, '''Unexpected errors in dm: «dmErrors.join(", ")»''')
		Assertions.assertNotNull(sm)
		val smErrors = sm.eResource.errors
		Assertions.assertTrue(smErrors.isEmpty, '''Unexpected errors in sm: «smErrors.join(", ")»''')
	}
}
