/*
 * generated by Xtext 2.16.0
 */
package com.mimacom.ddd.dm.dem.validation

import com.mimacom.ddd.dm.base.BasePackage
import com.mimacom.ddd.dm.base.DNamedElement
import org.eclipse.xtext.validation.Check
import com.mimacom.ddd.dm.dem.DemActor
import com.mimacom.ddd.dm.dem.DemDomainEvent
import com.mimacom.ddd.dm.dem.DemCaseConjunction
import com.mimacom.ddd.dm.dem.DemNotification

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class DemValidator extends AbstractDemValidator {
	
	static val BASE = BasePackage.eINSTANCE
	
	@Check
	def checkOtherwiseClause(DemDomainEvent event) {
		val caseConjunctions =  event.postconditionsDNF.filter(DemCaseConjunction)
		val countOtherwise = caseConjunctions.filter[isOtherwise].size
		if (countOtherwise == 1) {
			for(var i=0; i<caseConjunctions.size; i++) {
				if (caseConjunctions.get(i).isOtherwise && i !=caseConjunctions.size-1) {
					error ("The 'otherwise' clause must be last", caseConjunctions.get(i), BASE.DNamedElement_Name)
				}
			}
		} else if (countOtherwise > 1) {
			for(var i=0; i<caseConjunctions.size; i++) {
				if (caseConjunctions.get(i).isOtherwise) {
					error ("There can only be one 'otherwise' clause ", caseConjunctions.get(i), BASE.DNamedElement_Name)
				}
			}
		}
	}
	

	@Check
	def void checkTypeNameStartsWithCapital(DemActor a) {
		checkNameStartsWithCapital(a)
	}

	@Check
	def void checkTypeNameStartsWithCapital(DemDomainEvent de) {
		checkNameStartsWithCapital(de)
	}

	@Check
	def void checkTypeNameStartsWithCapital(DemNotification n) {
		checkNameStartsWithCapital(n)
	}
	

	def void checkNameStartsWithCapital(DNamedElement ne) {
		checkNameStartsWithCapitalImpl(ne.name, ne)
	}
	

	// // Naming: Elements whose names should start with a CAPITAL
	protected def void checkNameStartsWithCapitalImpl(String name, DNamedElement ne) {
		if (name !== null && name.length > 0 && !Character::isUpperCase(name.charAt(0))) {
			warning("Name should start with a capital", ne, BasePackage.Literals::DNAMED_ELEMENT__NAME)

		}
	}
}
