/**
 * generated by Xtext 2.16.0
 */
package com.mimacom.ddd.dm.dem;

import com.mimacom.ddd.dm.dem.AbstractDemRuntimeModule;
import com.mimacom.ddd.dm.dmx.parsing.DmxValueConverters;
import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DemRuntimeModule extends AbstractDemRuntimeModule {
  @Override
  public Class<? extends IValueConverterService> bindIValueConverterService() {
    return DmxValueConverters.class;
  }
}
