/**
 * generated by Xtext 2.16.0
 */
package com.mimacom.ddd.sm.sim;

import com.google.inject.Injector;
import com.mimacom.ddd.sm.sim.SimPackage;
import com.mimacom.ddd.sm.sim.SimStandaloneSetupGenerated;
import org.eclipse.emf.ecore.EPackage;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SimStandaloneSetup extends SimStandaloneSetupGenerated {
  public static void doSetup() {
    new SimStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
  
  @Override
  public void register(final Injector injector) {
    boolean _containsKey = EPackage.Registry.INSTANCE.containsKey(SimPackage.eNS_URI);
    boolean _not = (!_containsKey);
    if (_not) {
      EPackage.Registry.INSTANCE.put(SimPackage.eNS_URI, SimPackage.eINSTANCE);
    }
    super.register(injector);
  }
}
