/**
 * generated by Xtext 2.19.0
 */
package com.mimacom.ddd.dm.div.impl;

import com.mimacom.ddd.dm.base.transpose.impl.TInformationModelImplCustom;

import com.mimacom.ddd.dm.div.DivPackage;
import com.mimacom.ddd.dm.div.DomainInformationView;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Domain Information View</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DomainInformationViewImpl extends TInformationModelImplCustom implements DomainInformationView
{
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainInformationViewImpl()
	{
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass()
	{
		return DivPackage.Literals.DOMAIN_INFORMATION_VIEW;
	}

} //DomainInformationViewImpl
