/**
 * generated by Xtext 2.19.0
 */
package com.mimacom.ddd.pub.pub.ui.contentassist;

import com.mimacom.ddd.pub.pub.ui.contentassist.AbstractPubProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class PubProposalProvider extends AbstractPubProposalProvider {
}
