/*
 * generated by Xtext 2.19.0
 */
package com.mimacom.ddd.sm.asm.scoping;

import com.mimacom.ddd.dm.dmx.scoping.DmxScopeProvider;

public abstract class AbstractAsmScopeProvider extends DmxScopeProvider {
}
