<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="esm" nsURI="http://www.mimacom.com/ddd/dm/esm" nsPrefix="esm">
  <eClassifiers xsi:type="ecore:EClass" name="DEntityStateModel" eSuperTypes="../../com.mimacom.ddd.dm.base/model/base.ecore#//DNamedElement ../../com.mimacom.ddd.dm.base/model/base.ecore#//IIdentityStateModel ../../com.mimacom.ddd.dm.base/model/base.ecore#//INavigableMemberContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//DState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//DEvent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//DTransition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DState">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DTransition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//DState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//DState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//DEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DExpression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
