<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="esm" nsURI="http://www.mimacom.com/ddd/dm/esm" nsPrefix="esm">
  <eClassifiers xsi:type="ecore:EClass" name="EsmDomain" eSuperTypes="../../com.mimacom.ddd.dm.base/model/base.ecore#//DNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DImport"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateModel" eType="#//EsmEntityStateModel"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EsmEntityStateModel" eSuperTypes="../../com.mimacom.ddd.dm.base/model/base.ecore#//DNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//EsmState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forType" eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DEntityType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//EsmTransition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EsmState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EsmTransition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//EsmState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//EsmState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DStateEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DExpression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
