<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="esm" nsURI="http://www.mimacom.com/ddd/dm/esm" nsPrefix="esm">
  <eClassifiers xsi:type="ecore:EClass" name="EsmEntityStateModel" eSuperTypes="../../com.mimacom.ddd.dm.base/model/base.ecore#//DModel #//IEsmStateModel ../../com.mimacom.ddd.dm.base/model/base.ecore#//INavigableMemberContainer ../../com.mimacom.ddd.dm.base/model/base.ecore#//IStaticReferenceTarget ../../com.mimacom.ddd.dm.base/model/base.ecore#//IDiagramRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="forType" eType="ecore:EClass ../../com.mimacom.ddd.dm.dim/model/dim.ecore#//DimEntityType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IEsmLayout" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//EsmLayoutDirection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IEsmStateModel" abstract="true" interface="true"
      eSuperTypes="#//IEsmLayout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//IEsmState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//EsmTransition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EsmLayoutDirection">
    <eLiterals name="DEFAULT"/>
    <eLiterals name="DOWN" value="1"/>
    <eLiterals name="LEFT" value="2"/>
    <eLiterals name="UP" value="3"/>
    <eLiterals name="RIGHT" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IEsmState" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//EsmStateKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DRichText"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EsmStateKind">
    <eLiterals name="NORMAL"/>
    <eLiterals name="INITIAL" value="1"/>
    <eLiterals name="FINAL" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EsmState" eSuperTypes="#//IEsmState"/>
  <eClassifiers xsi:type="ecore:EClass" name="EsmDerivedState" eSuperTypes="#//EsmState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EsmCompositeState" eSuperTypes="#//IEsmState #//IEsmStateModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="EsmConcurrentState" eSuperTypes="#//IEsmState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subStates" upperBound="-1"
        eType="#//EsmSubStateModel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EsmSubStateModel" eSuperTypes="#//IEsmStateModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="EsmTransition" eSuperTypes="#//IEsmLayout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DStateEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DExpression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
