grammar com.mimacom.ddd.dm.dom.Dom with  com.mimacom.ddd.dm.dmx.Dmx

import "http://www.mimacom.com/ddd/dm/dom"
import "http://www.mimacom.com/ddd/dm/dmx"
import "http://www.mimacom.com/ddd/dm/base" 

DomModel:
	(imports+=DImport)*
	'domain'
	name=DQualifiedName
	(snapshots+=DomSnapshot)+;

DomSnapshot:
	'snapshot' name=ID
	'{'
	(objects+=DomObject)*
	'}';

DomObject:
	DomNamedComplexObject;
	
DomNamedComplexObject:
	name=ID
	'=' 
	object=(DmxEntity | DmxDetail);
