/*
 * generated by Xtext 2.17.1
 */
package com.mimacom.ddd.dm.dom


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DomRuntimeModule extends AbstractDomRuntimeModule {
}
