grammar com.mimacom.ddd.sm.sus.Sus with com.mimacom.ddd.pub.pub.Pub

import "http://www.mimacom.com/ddd/sm/sus"
import "http://www.mimacom.com/ddd/dm/base" 
import "http://www.mimacom.com/ddd/dm/dem" 

@Override 
DNamespace:
	'system'
	name=DQualifiedName
	(imports+=DImport)*
	model=UserStory; 
	
UserStory:
	'user' 'story'
	name=DQualifiedName
	(	('realises' | 'realizes')
		event=[DemDomainEvent|DQualifiedName]
	)?
	(description=DRichText)?
	'goal' 
	goal=DRichText
	(sections+=PubSection)*;
