/**
 * generated by Xtext 2.17.1
 */
package com.mimacom.ddd.dm.esm;

import com.mimacom.ddd.dm.base.base.DModel;
import com.mimacom.ddd.dm.base.base.IDiagramRoot;
import com.mimacom.ddd.dm.base.base.INavigableMemberContainer;
import com.mimacom.ddd.dm.base.base.INoteContainer;
import com.mimacom.ddd.dm.base.base.IStaticReferenceTarget;

import com.mimacom.ddd.dm.dim.DimEntityType;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity State Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.mimacom.ddd.dm.esm.EsmEntityStateModel#getForType <em>For Type</em>}</li>
 * </ul>
 *
 * @see com.mimacom.ddd.dm.esm.EsmPackage#getEsmEntityStateModel()
 * @model
 * @generated
 */
public interface EsmEntityStateModel extends DModel, INoteContainer, IEsmStateModel, INavigableMemberContainer, IStaticReferenceTarget, IDiagramRoot
{
	/**
	 * Returns the value of the '<em><b>For Type</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>For Type</em>' reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>For Type</em>' reference.
	 * @see #setForType(DimEntityType)
	 * @see com.mimacom.ddd.dm.esm.EsmPackage#getEsmEntityStateModel_ForType()
	 * @model
	 * @generated
	 */
	DimEntityType getForType();

	/**
	 * Sets the value of the '{@link com.mimacom.ddd.dm.esm.EsmEntityStateModel#getForType <em>For Type</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>For Type</em>' reference.
	 * @see #getForType()
	 * @generated
	 */
	void setForType(DimEntityType value);

} // EsmEntityStateModel
