<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dem" nsURI="http://www.mimacom.com/ddd/dm/dem" nsPrefix="dem">
  <eClassifiers xsi:type="ecore:EClass" name="DemDomainEvent" eSuperTypes="../../com.mimacom.ddd.dm.base/model/base.ecore#//DModel ../../com.mimacom.ddd.dm.base/model/base.ecore#//INoteContainer ../../com.mimacom.ddd.dm.base/model/base.ecore#//INavigableMemberContainer ../../com.mimacom.ddd.dm.base/model/base.ecore#//IStaticReferenceTarget ../../com.mimacom.ddd.dm.base/model/base.ecore#//IDiagramRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DContext"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" lowerBound="1"
        upperBound="-1" eType="#//DemActor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preconditionsCNF" upperBound="-1"
        eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DNamedPredicate"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postconditionsDNF" upperBound="-1"
        eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DNamedElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notifications" upperBound="-1"
        eType="#//DemNotification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DemCaseConjunction" eSuperTypes="../../com.mimacom.ddd.dm.base/model/base.ecore#//DNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="selector" eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="otherwise" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicates" upperBound="-1"
        eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DNamedPredicate"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DemNotification" eSuperTypes="../../com.mimacom.ddd.dm.base/model/base.ecore#//DNavigableMember ../../com.mimacom.ddd.dm.base/model/base.ecore#//INavigableMemberContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" eType="#//DemMessage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notified" lowerBound="1"
        eType="#//DemActor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DemMessage" eSuperTypes="../../com.mimacom.ddd.dm.base/model/base.ecore#//DNavigableMember"/>
  <eClassifiers xsi:type="ecore:EClass" name="DemActorModel" eSuperTypes="../../com.mimacom.ddd.dm.base/model/base.ecore#//DModel ../../com.mimacom.ddd.dm.base/model/base.ecore#//INoteContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actors" upperBound="-1"
        eType="#//DemActor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DemActor" abstract="true" eSuperTypes="../../com.mimacom.ddd.dm.base/model/base.ecore#//DNavigableMember ../../com.mimacom.ddd.dm.base/model/base.ecore#//IStaticReferenceTarget"/>
  <eClassifiers xsi:type="ecore:EClass" name="DemHumanActorRole" eSuperTypes="#//DemActor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DemService" eSuperTypes="#//DemActor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DemEventsOverviewModel" eSuperTypes="../../com.mimacom.ddd.dm.base/model/base.ecore#//DModel ../../com.mimacom.ddd.dm.base/model/base.ecore#//INoteContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="all" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="include" upperBound="-1"
        eType="#//DemDomainEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exclude" upperBound="-1"
        eType="#//DemDomainEvent"/>
  </eClassifiers>
</ecore:EPackage>
