<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sus" nsURI="http://www.mimacom.com/ddd/sm/sus" nsPrefix="sus">
  <eClassifiers xsi:type="ecore:EClass" name="UserStory" eSuperTypes="../../com.mimacom.ddd.dm.base/model/base.ecore#//DNamespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sections" upperBound="-1"
        eType="#//Section" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="ecore:EClass ../../com.mimacom.ddd.dm.dem/model/dem.ecore#//DDomainEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Section">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paragraphs" upperBound="-1"
        eType="#//Paragraph" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Paragraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="ecore:EClass ../../com.mimacom.ddd.dm.base/model/base.ecore#//DRichText"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
