/*
 * generated by Xtext 2.16.0
 */
package com.mimacom.ddd.dm.dim.ui.tests;

import com.google.inject.Injector;
import com.mimacom.ddd.dm.dim.ui.internal.DimActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DimUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DimActivator.getInstance().getInjector("com.mimacom.ddd.dm.dim.Dim");
	}

}
