<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="base" nsURI="http://www.mimacom.com/ddd/dm/base" nsPrefix="base">
  <eClassifiers xsi:type="ecore:EClass" name="INamespace" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ITypeContainer" abstract="true" interface="true"
      eSuperTypes="#//INamespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//DType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDeductionDefinition" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deductionRule" eType="#//DDeductionRule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDeducibleElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deducedFrom" eType="#//IDeductionDefinition"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="synthetic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DDeductionRule" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//IDeducibleElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namedSource" eType="#//DNamedElement"
        changeable="false" transient="true" derived="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DNamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aliases" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#//DRichText"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DNavigableMember" abstract="true" eSuperTypes="#//DNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//DType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" eType="#//DMultiplicity"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collection" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="INavigableMemberContainer" abstract="true"
      interface="true" eSuperTypes="#//INamespace"/>
  <eClassifiers xsi:type="ecore:EClass" name="IStaticReferenceTarget" abstract="true"
      interface="true" eSuperTypes="#//DNamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="IRichTextSegment" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DTextSegment" eSuperTypes="#//IRichTextSegment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DExpression" abstract="true" eSuperTypes="#//IRichTextSegment"/>
  <eClassifiers xsi:type="ecore:EClass" name="DRichText" eSuperTypes="#//DExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="segments" upperBound="-1"
        eType="#//IRichTextSegment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DImport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DDomain" eSuperTypes="#//DNamedElement #//ITypeContainer #//IStaticReferenceTarget #//IDeducibleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//DImport" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregates" upperBound="-1"
        eType="#//DAggregate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateModels" upperBound="-1"
        eType="#//IIdentityStateModel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//DDomainEvent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actors" upperBound="-1"
        eType="#//DActor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAggregate" eSuperTypes="#//DNamedElement #//ITypeContainer #//INavigableMemberContainer #//IStaticReferenceTarget #//IDeducibleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roots" unique="false" upperBound="-1"
        eType="#//DIdentityType" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="staticQueries" upperBound="-1"
        eType="#//DQuery" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IIdentityType" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IValueType" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DType" abstract="true" eSuperTypes="#//DNamedElement #//IDeducibleElement #//IStaticReferenceTarget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//DNamedPredicate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DNamedPredicate" eSuperTypes="#//DNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" eType="#//DExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DSimpleType" abstract="true" eSuperTypes="#//DType #//IValueType"/>
  <eClassifiers xsi:type="ecore:EClass" name="DPrimitive" eSuperTypes="#//DSimpleType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefines" eType="#//DPrimitive"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DEnumeration" eSuperTypes="#//DSimpleType #//INavigableMemberContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//DLiteral" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DLiteral" eSuperTypes="#//DNavigableMember #//IDeducibleElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DComplexType" abstract="true" eSuperTypes="#//DType #//INavigableMemberContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//DComplexType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//DFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DDetailType" eSuperTypes="#//DComplexType #//IValueType"/>
  <eClassifiers xsi:type="ecore:EClass" name="DIdentityType" abstract="true" eSuperTypes="#//DComplexType #//IIdentityType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="root" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="origin" eType="#//DIdentityOrigin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DIdentityOrigin">
    <eLiterals name="REAL_WORLD_OBJECT"/>
    <eLiterals name="VIRTUAL_CONCEPT" value="1"/>
    <eLiterals name="GENERIC_ENTITY" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IIdentityStateModel" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="forType" eType="#//DIdentityType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DEntityType" eSuperTypes="#//DIdentityType"/>
  <eClassifiers xsi:type="ecore:EClass" name="DRelationship" eSuperTypes="#//DIdentityType"/>
  <eClassifiers xsi:type="ecore:EClass" name="DFeature" abstract="true" eSuperTypes="#//DNavigableMember #//IDeducibleElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DAssociation" eSuperTypes="#//DFeature">
    <eOperations name="getTargetType" eType="#//DEntityType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//DAssociationKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceType" unique="false"
        lowerBound="1" eType="#//DComplexType" changeable="false" volatile="true"
        transient="true" derived="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DAssociationKind">
    <eLiterals name="REFERENCE"/>
    <eLiterals name="COMPOSITE" value="1"/>
    <eLiterals name="INVERSE_COMPOSITE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DMultiplicity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minOccurs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxOccurs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAttribute" eSuperTypes="#//DFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="detail" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DQuery" eSuperTypes="#//DFeature #//INavigableMemberContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//DQueryParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returns" eType="#//DExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DQueryParameter" eSuperTypes="#//DNavigableMember #//IDeducibleElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DDomainEvent" eSuperTypes="#//DNamedElement #//INavigableMemberContainer #//IStaticReferenceTarget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        upperBound="-1" eType="#//DContext" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" lowerBound="1"
        eType="#//DActor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preconditionsCNF" upperBound="-1"
        eType="#//DNamedPredicate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postconditionsDNF" upperBound="-1"
        eType="#//DNamedElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notifications" upperBound="-1"
        eType="#//DNotification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DCaseConjunction" eSuperTypes="#//DNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="selector" eType="#//DExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicates" upperBound="-1"
        eType="#//DNamedPredicate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DContext" eSuperTypes="#//DNavigableMember"/>
  <eClassifiers xsi:type="ecore:EClass" name="DNotification" eSuperTypes="#//DNavigableMember #//INavigableMemberContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" eType="#//DMessage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notified" lowerBound="1"
        eType="#//DActor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DMessage" eSuperTypes="#//DNavigableMember"/>
  <eClassifiers xsi:type="ecore:EClass" name="DActor" abstract="true" eSuperTypes="#//DNamedElement #//IStaticReferenceTarget"/>
  <eClassifiers xsi:type="ecore:EClass" name="DHumanActorRole" eSuperTypes="#//DActor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" eType="#//DIdentityType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DService" eSuperTypes="#//DActor"/>
</ecore:EPackage>
