/*
 * generated by Xtext 2.19.0
 */
package com.mimacom.ddd.pub.pub


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PubStandaloneSetup extends PubStandaloneSetupGenerated {

	def static void doSetup() {
		new PubStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
