/**
 * generated by Xtext 2.17.1
 */
package com.mimacom.ddd.sm.asm;

import com.mimacom.ddd.dm.base.DNavigableMember;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SService Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.mimacom.ddd.sm.asm.SServiceParameter#getDirection <em>Direction</em>}</li>
 * </ul>
 *
 * @see com.mimacom.ddd.sm.asm.AsmPackage#getSServiceParameter()
 * @model
 * @generated
 */
public interface SServiceParameter extends DNavigableMember
{
	/**
	 * Returns the value of the '<em><b>Direction</b></em>' attribute.
	 * The literals are from the enumeration {@link com.mimacom.ddd.sm.asm.SDirection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Direction</em>' attribute.
	 * @see com.mimacom.ddd.sm.asm.SDirection
	 * @see #setDirection(SDirection)
	 * @see com.mimacom.ddd.sm.asm.AsmPackage#getSServiceParameter_Direction()
	 * @model
	 * @generated
	 */
	SDirection getDirection();

	/**
	 * Sets the value of the '{@link com.mimacom.ddd.sm.asm.SServiceParameter#getDirection <em>Direction</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Direction</em>' attribute.
	 * @see com.mimacom.ddd.sm.asm.SDirection
	 * @see #getDirection()
	 * @generated
	 */
	void setDirection(SDirection value);

} // SServiceParameter
