<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dom" nsURI="http://www.mimacom.com/ddd/dm/dom" nsPrefix="dom">
  <eClassifiers xsi:type="ecore:EClass" name="DomModel" eSuperTypes="../../com.mimacom.ddd.dm.base/model/base.ecore#//DModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="snapshots" upperBound="-1"
        eType="#//DomSnapshot" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomSnapshot" eSuperTypes="../../com.mimacom.ddd.dm.base/model/base.ecore#//DNamedElement ../../com.mimacom.ddd.dm.base/model/base.ecore#//INoteContainer ../../com.mimacom.ddd.dm.base/model/base.ecore#//INavigableMemberContainer ../../com.mimacom.ddd.dm.base/model/base.ecore#//IDiagramRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="#//DomObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomObject" abstract="true" eSuperTypes="../../com.mimacom.ddd.dm.base/model/base.ecore#//DNavigableMember"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomNamedComplexObject" eSuperTypes="#//DomObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="ecore:EClass ../../com.mimacom.ddd.dm.dmx/model/dmx.ecore#//DmxComplexObject"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
