/*
 * generated by Xtext 2.19.0
 */
package com.mimacom.ddd.sm.sim.ui.tests;

import com.google.inject.Injector;
import com.mimacom.ddd.sm.sim.ui.internal.SimActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SimUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SimActivator.getInstance().getInjector("com.mimacom.ddd.sm.sim.Sim");
	}

}
