/*
 * generated by Xtext 2.16.0
 */
package com.mimacom.ddd.dm.dms.parser.antlr;

import com.google.inject.Inject;
import com.mimacom.ddd.dm.dms.parser.antlr.internal.InternalDmsParser;
import com.mimacom.ddd.dm.dms.services.DmsGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DmsParser extends AbstractAntlrParser {

	@Inject
	private DmsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDmsParser createParser(XtextTokenStream stream) {
		return new InternalDmsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DModel";
	}

	public DmsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DmsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
