/*
 * generated by Xtext 2.19.0
 */
package com.mimacom.ddd.im.generator;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GeneratorStandaloneSetup extends GeneratorStandaloneSetupGenerated {

	public static void doSetup() {
		new GeneratorStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
