/**
 * generated by Xtext 2.17.1
 */
package dem;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Actor Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dem.DemActorModel#getActors <em>Actors</em>}</li>
 * </ul>
 *
 * @see dem.DemPackage#getDemActorModel()
 * @model abstract="true"
 * @generated
 */
public interface DemActorModel extends DemModel
{
	/**
	 * Returns the value of the '<em><b>Actors</b></em>' containment reference list.
	 * The list contents are of type {@link dem.DActor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Actors</em>' containment reference list.
	 * @see dem.DemPackage#getDemActorModel_Actors()
	 * @model containment="true"
	 * @generated
	 */
	EList<DActor> getActors();

} // DemActorModel
